### ISSUE TITLE
брифинг: Много ошибок пунктукции и стилистичексие

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/co25_DarkHolme.lingor3#13]

**Comment by 1im** [comment]
где, в каком параграфе, что не понравилось? ссылки в студию

**Comment by 10Dozen** [comment]
>Неделю назад наш FOB на востоке

Какой наш? Кто такие мы? На карте 4 фоба подписано, но в брифинге какойто ФОБ из легенд и преданий?

>сообщают что

Где запитая?

> информаторы сообщают что **часть** находящегося там взвода **выжили** и **попали**

Часть - она, выжили - они

>в этом лагере, и может 

зачем тут запятая?

>Один из наших информаторов находится

Что это за информатор такой? Как его отделить от прочих вьетнамцев чтобы не убить?

>в районе Echo, Eddie или Zanjeer
>M113 на Echo

Как называется религия которая резрешает писать ФОБ на карте, но карает за ФОБ в тексте?

>Нашим информатором в POW Camp является офицер NVA, у его казармы установлен красный флагшток.

Охуительные истории, 10 из 10, оскар за судьбу вьетнамца гомосексуалиста оказавшимся информатором США для того чтобы его забрали в америку и сделали силиконовые сиськи. Кароч очень реалистично, гандамы тоже будут? И что такое NVA? NuVista Energy Ltd.? И почему наш информатор не смог указать на карте где он обитает? Его от американских снарядов защитит мистер Диксон?

>в районе 'POW Camp'
>на FOB X-Ray

У вас двойные стандарты

>1) **сд**елать высадку на вертолете
>3) **З**аказать осветительные

И биг мак? У кого заказать? Ты то их тестил, эти осветительные?

>IV. Поддержка:

Пункт целиком посвящен твоей шизофрении. Прими таблеток и напиши на русском, английский в жопку засунь если тебе так нравится

>VI. Замечания:

Действительно, у нас же тут миссия чтобы потешить самолюбие, а не играть. Нахуя писать какие-либо замечания.

>b) Заролеплеить зевсом допрос раненного вражины и сделать

Сразу нахуй. Сделал говно, нехуй его и играть

>- Пленные будут посчитаны на X-Ray только когда им развяжут руки

Как будто ГСО не похуй? Зачем это знать ГСО? Я просто зафейлю ее в таком случае, раз мишн мейкеру вообще до пизды.

**Comment by 1im** [comment]
ок, пошел фиксить
пиздец ты токсичный конечно, таблеточек накати а то как критические дни

**Comment by 10Dozen** [comment]
Может ты мексидола ебнешь или там чего что укрепит психику? У тебя каждое новое предложение как будто другой человек пишет, это НЕ нормально.
