### ISSUE TITLE
Брифинг - Поддержка

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/co25_DarkHolme.lingor3#17]
- Что значит АУТО_ПАЙЛОТ ?
- Что значит +- CCP ?
- Что делает М113 с М240 во Вьетнаме? Годы эксплуатации | 1977 год — настоящее время
- Почему Artillery а не какая нить 砲兵 ? Очень органично будет смотреться
- Артиллерия ручная?

**Comment by 1im** [comment]
>     Что значит АУТО_ПАЙЛОТ ?
изменил на (Piloted by AI)

>    Что значит +- CCP ?
изменил на CCP deployment allowed

>    Что делает М113 с М240 во Вьетнаме? Годы эксплуатации | 1977 год — настоящее время

removed

>    Почему Artillery а не какая нить 砲兵 ? Очень органично будет смотреться
>    Артиллерия ручная?

Заменил на Steel Rain - M252 Battery (Provided by AI)

**Comment by 10Dozen** [comment]
Нахуя на английском то? なぜ日本語ではないのですか？

**Comment by 1im** [comment]
бля ну наверное надо писать - пиши на русский сразу в тикете, не?
ща поменяю

**Comment by 10Dozen** [comment]
Ну наверное ОЧЕВИДНО ДЛЯ ЗДРАВОМЫСЛЯЩИХ ЛЮДЕЙ ЧТО ЕСЛИ ВЕСЬ БРИФИНГ РУССКИМИ БУКВАМИ ТО НЕ НАДО БЫТЬ ШИЗОФРЕНИКОМ И ПИСАТЬ В СЕРЕДИНЕ НА АНГЛЙИСКОМ, 
# НЕ?
