### ISSUE TITLE
Интро: Шизофренический набор букв

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/co25_DarkHolme.lingor3#19]
- VietNam почеМуто пиШется в кеМелКейСе
- Все схуЯто на анГлийсКом
- КакоГо хуЯ "Хуюнел Ратс, зе" ? Чо блять? Чойто за говно?

**Comment by 1im** [comment]
fixed
https://github.com/rempopo/co25_Tunnel_Rats.lingor3/commit/e7a1f6c5c17656569d87113b7c258191384fc42b
