### ISSUE TITLE
В ящиках КУПовские М72А6 + ящики перегружены полусотянми магазинов и гранат

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/co25_DarkHolme.lingor3#20]

**Comment by 1im** [comment]
выпилил трубы, понерфил количество магазов и гранат
https://github.com/rempopo/co25_Tunnel_Rats.lingor3/blob/01979aa27b56f1f5ee082ecb7e167cbcefc1409b/dzn_gear/Kits.sqf#L129-L134
