### ISSUE TITLE
Чото не хочет свет работать над входом в тунель

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/co25_DarkHolme.lingor3#24]

**Comment by 1im** [comment]
не понял, подробнее можно?

**Comment by 10Dozen** [comment]
Подробнее: ТЕСТИРОВАЛИ ЛИ ОСВЕЩЕНИЕ АРТОЙ ИЛИ КАК ОБЫЧНО ДРИСТАНУЛИ МИССИЮ С ДЕВИЗОМ "И ТАК СОЙДЕТ"?

**Comment by 1im** [comment]
ок, тестану, а так с фонариком проверял
