### ISSUE TITLE
Каким образом в темноте нужно найти кусок маск сетки 1х1.5 метра в окружении зеленки?

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/co25_DarkHolme.lingor3#25]
Для кого эта миссия? Зачем она нужна? Потешить самолюбие создателя? Типа ахахаха ну вы придурки не смогли догадаться что вход в туннель ГДЕТО В ЛЕСУ В РАДИУСЕ 500 МЕТРОВ ОТ МАРКЕРА, ебать вы долбоебы

**Comment by 1im** [comment]
добавил описание в разговор с информатором
"We moved the rest of POWs into the tunnels around this village. You have to circle around in the woods a bit. Entries are hidden away by lots of tall banana bushes. Those will be the tallest plants in the jungle"
Достаточно подробно?

олсо, там макс 100 метров от домов

**Comment by 10Dozen** [comment]
Ночью, в темноте, искать что-то чего никогда в жизни не видел по текстовому описанию на английском? Хуйня, Мишаня, давай по новой

**Comment by 1im** [comment]
Мы перевели остальных пленных в туннели под этой деревней (помечает на карте). Прочешите джунгли вокруг деревни и вы найдёте входы в туннели. Они накрыты камуфляжной сеткой и прикрыты крупными банановыми кустами, это будут самые высокие растения в джунглях, ну кроме самих деревьев?

так лучше?

**Comment by 10Dozen** [comment]
Нет, у тебя тут раздвоение пошло личности. Сначала ты всем говоришь что нельзя делать миссии где сюжет меняется на ходу, потом делаешь такую в худшем ее проявлении.

Во-первых, изучи theory of mind
Во-втрых, если ты прочитал в редакторе что кусты называются БАНАНА и увидел как они выглядят, то это не значит что игроки знают или их вообще ебет как выглядят банановые кусты
В-третьих, стена английского текста в хинте скорее всего не будет прочитано большинством (это если она вообще рисуется для всех, а не для одного пацана)
В-четвертых, сходу после перестрелки понять о чем пиздит крокодил - очень сложно
В-пятых, ночью в темноте с хуевым освещением ходить по лесу полному врагов и искать какуюто хуйню в неизвестном месте - такое себе занятие - уровня русланда, еще обидку можешь кинуть что ТИПА КАРЛ НУ КАРЛ ТУТ ЖЕ ОЧЕВИДНО КАРЛ НУ ЧТО ТЫ ТУПИШЬ НУ ОЧЕВИДНО ЖЕ Я САМ В РЕДАКТОРЕ СТАВИЛ
В-шестых, У ТЕБЯ БЛЯТЬ С САМОГО НАЧАЛА МИССИИ НА ПОЛ КАРТЫ КАКАЯТО ЧОРНАЯ ХУЙНЯ С НАДПИСЬЮ ТУННЕЛ МАП - ЙОБ ТВОЮ МАТЬ, КАКОГО ХУЯ ТЫ ИЗ ЭТОГО ДЕЛАЕШЬ ПЛОТВТИСТ ЕСЛИ БЛЯТЬ С САМОГО ЕБАНОГО НАЧАЛА ОГРОМНАЯ НАДПИСЬ ТУНЕЛЬ МАП - НО НЕТ, О НИХ НИКТО НЕ ЗНАЕТ, МЫ ВАМ ДАДИМ БЛОКНОТИК ЧТОБЫ НУ НА ВСЯКИЙ СЛУЧАЙ А ГДЕ И ЧО ЭТО НИКТО ДАЖЕ ПОДУМАТЬ НЕ МОГ , МЫ Ж ВСЕГО ТО ГОВНОСША ОТКУДА У НАС РАЗВЕДКА ТОЛЬКО КУПИЛИ **НАЧАЛЬНИКА ЛАГЕРЯ** ПРО ТУНЕЛИ ТО НАМ НЕ ЗНАТЬ - А ЧО ВООБЩЕ МОЖНО ПОД ЗЕМЛЕЙ ЧТОТО РЫТЬ?! ВАУ
