### ISSUE TITLE
Что за ковер с оленями внутри?

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/co25_DarkHolme.lingor3#26]

**Comment by 1im** [comment]
чтобы прикрыть корридор на выход сделанный из контейнера

**Comment by 10Dozen** [comment]
Ну так снаружи маск сеть - повесь и сюда масксеть

**Comment by 1im** [comment]
интеракшн вешается на только на колижн геометрии, т.е. на углы и балки а не всю маск сеть
ты уверен что стоит заменить ковры?

**Comment by 10Dozen** [comment]
Мне допесды, не я же делаю миссию. Ты все масксети пробовал?
