### ISSUE TITLE
Обновить киты

### ISSUE THREAD

**Issue by OneScheer** [rempopo/co25_DarkHolme.lingor3#28]
Заменить униформу и снаряжение CUP на добавленные OG-107 и M1 из мода RHS GREF

**Comment by OneScheer** [comment]
Ну и что ты обновил?

**Comment by 1im** [comment]
https://github.com/rempopo/co25_Tunnel_Rats.lingor3/commit/571d452662d123fd75d81d6d902db99be4a558c6

fixed
