### ISSUE TITLE
Неработающие условия

### ISSUE THREAD

**Issue by OneScheer** [rempopo/co25_DarkHolme.lingor3#8]
Сразу же после запуска миссии выполняется условие MissionCondition2 - "Часть пленных спасены".

**Comment by 1im** [comment]
git pull
попробуй исправленное

**Comment by 1im** [comment]
https://github.com/rempopo/co25_DarkHolme.lingor3/blob/9a26fdb8828d1ea73747cb3b640433ca51bb8060/dzn_tSFramework/Modules/MissionConditions/Settings.sqf#L56-L59

кароч вот так выглядит, все работает
