### ISSUE TITLE
Униформа CUP и разгрузки USM несовместимы

### ISSUE THREAD

**Issue by OneScheer** [rempopo/co25_DarkHolme.lingor3#9]
![20180523134332_1](https://user-images.githubusercontent.com/20025467/40419928-683a996e-5e8f-11e8-9b32-8de6db14202c.jpg)

**Comment by 1im** [comment]
по мне и так нормас, сверху рюкзаком накрыть и норм, не?

**Comment by 1im** [comment]
https://github.com/rempopo/co25_DarkHolme.lingor3/blob/6cde6d946a71def40208589caa2f64f9d1c86cfb/dzn_gear/Kits.sqf#L85-L86

fixed
